version: '2.1'

services:
  database:
    hostname: database
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD","/bin/sh","-i","-c", "MYSQL_PWD=\"${MYSQL_PASSWORD}\" mysql -h 127.0.0.1 -u ${MYSQL_USER} -D ${MYSQL_DATABASE} -e 'SELECT 1'"]
      interval: 3s
      timeout: 10s
      retries: 20

  entando-avatar-plugin:
    image: entando/entando-avatar-plugin:5.2.0-SNAPSHOT
    hostname: entando-avatar-plugin
    environment:
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/${MYSQL_DATABASE}
      SPRING_PROFILES_ACTIVE: prod,swagger
    depends_on:
      database:
        condition: service_healthy

  smoke-test:
    image: entando/entando-spring-actuator-test:5.2.0-SNAPSHOT
    environment:
      SPRING_BOOT_BASE_URL: http://entando-avatar-plugin:8081/avatarPlugin/management
      INTERVAL: 3
      MAX_ATTEMPTS: 30



